"""Add document metadata and share unique constraint

Revision ID: ca9615ef4c1e
Revises: 839f036abec4
Create Date: 2026-09-11 14:39:13.163249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9615ef4c1e'
down_revision = '839f036abec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_shares', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_document_share_target', ['document_id', 'shared_with_id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('description')

    with op.batch_alter_table('document_shares', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_share_target', type_='unique')

    # ### end Alembic commands ###
