"""add file cleanup jobs

Revision ID: d1c8d011d096
Revises: d4b7a1c92e60
Create Date: 2026-09-15 16:49:43.821046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c8d011d096'
down_revision = 'd4b7a1c92e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_cleanup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id_snapshot', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_file_cleanup_jobs_status'),
    sa.CheckConstraint('attempt_count >= 0 AND attempt_count <= 5', name='ck_file_cleanup_jobs_attempt_count'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_cleanup_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_cleanup_jobs_document_id_snapshot'), ['document_id_snapshot'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_cleanup_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_cleanup_jobs_document_id_snapshot'))

    op.drop_table('file_cleanup_jobs')
    # ### end Alembic commands ###
